### ISSUE TITLE
Features: Re: Server headings

### ISSUE THREAD

**Issue by sjimellor-jr** [jumpingrivers/audit.base#15]
The "Server headings" suite of tests seems like it could benefit from a few more tests:

- [ ] Is SSL enabled/in use?
  - critical for security
- [ ] Is the SSL certificate trusted?
  - critical for functionality
- [ ] Is the SSL certificate valid for at least 30 days?
  - 'important' but not critical, it may be auto-renewing at ~3 days
- [ ] Is the Secure flag set on Cookies?
  - important
- [ ] Is the minimum TLS version high enough?
  - depends
- [ ] Is stapling enabled?
  - very optional
- [ ] Is the server using a domain name?
  - important for user experience
- [ ] Is the server on a non-standard port?
  - important for user experience
- [ ] Is redirection from 80 to 443 enabled?
  - critical
- [ ] Is CORS configured?
  - depends
- [ ] SameSite cookies?
  - differs between Connect/Workbench depending on use case
- [ ] HSTS for subdomains?

**Comment by csgillespie** [comment]
@sjimellor-jr This is little bit like a dumping ground. Can you separate out into separate issues.

For info my thoughts are

 * HSTS - out  of scope
 *  Is the SSL certificate trusted? - no idea how to do this
 * Is the server using a domain name? - out of scope
 * Is the SSL certificate valid for at least 30 days? - is this a pain as caddy renews at the last minute (?) I think

**Comment by csgillespie** [comment]
For info, the following have now been added:

* 80 -> 443 redirection
* Is SSL enabled/in use?
